name: Pull request
on:
  pull_request:

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
        id: ACTIONS_ALLOW_UNSECURE_COMMANDS
        run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
        
      - run: echo ::set-env name=pull_number::$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)
      
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@master
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          SLACK_CHANNEL: hackday
          SLACK_MESSAGE: 'Please review on https://github.com/singhaniashrinkhala/PeerBot/pull/${{ env.pull_number}}'
          SLACK_TITLE: 'Pull request'
          SLACK_USERNAME: 'shrinkhala singhania'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
